[project]
name = "python_template_repo"
version = "0.0.0"
description = "A small example package"
authors = [
    {name = "Lennard Wolf", email = "7870758+MultifokalHirn@users.noreply.github.com"},
]
requires-python = ">=3.9"
readme = "README.md"
license = {text = "MIT"}
dependencies = [
    "pydantic",
    "ruamel-yaml",
    "termcolor",
    "typing-extensions",
    "types-requests",
    "types-mock",
    "types-pyyaml",
    "devtools"
]

[tool.pdm.dev-dependencies]
base = [
    "pre-commit",
    "commitizen",
]
lint = [
    "autopep8",
    "flake8",
    "mypy",
    "mypy-extensions",
]
test = [
    "pytest",
    "pytest-cov",
    "pytest-mypy",
    "pytest-xdist",
]
doc = ["mkdocs"]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
