# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run Checks on Code

on:
  #   push:
  #     branches: [ "main" ]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Lint & Test for ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      # fail-fast: true
      matrix:
        python-version: [3.8, 3.11]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}-dev

      - name: Install dependencies
        run: |
          make bootstrap
          make dev

      - name: Lint with flake8
        run: make lint
        continue-on-error: true
      - name: Test with pytest
        run: make test
